name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build --no-restore
    - name: dotnet test
      run: dotnet test --no-build --verbosity normal
    - name: Publish to nuget.org
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: JWTDecoder/JWTDecoder.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
      
